title: vinhminh # CV
description: | # VM ，<br/>VM
  Hobbies<br/>
  Backpacking, Fishing<br/>
  Game, Movies, Books<br/>
  <a href="mailto:vinhminhthan@gmail.com">
    <i class="fas fa-envelope"></i>
  </a>
  <a href="https://www.facebook.com/ga.gapro.5">
    <i class="fab fa-facebook"></i>
  </a>
  <a href="https://www.linkedin.com/in/minh-v%C4%A9nh-6baba899/">
    <i class="fas fa-linkedin-in"></i>
  </a>
  <iframe
    src="https://music.163.com/outchain/player?type=0&id=155059595&auto=0&height=32"
    width=100%
    height=52
    frameborder="no"
    border="0"
    marginwidth="0"
    marginheight="0"
  ></iframe>
url: https://wu-kan.cn # 你的域名，例如 https://wu-kan.github.io	url: https://wu-kan.cn # 你的域名，例如 https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。	baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。


@@ -62,11 +78,67 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
          rel="stylesheet"	          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"	          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
        />	        />
      - | # 引入live2d看板娘！不需要可以把这一项都删掉	        <script
        <link	          async="async"
          rel="stylesheet"	          src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"	          onload='
        />	              let pio_container = document.createElement("div");
              pio_container.classList.add("pio-container");
              pio_container.classList.add("right");
              pio_container.style.bottom = "-2rem";
              pio_container.style.zIndex = "1";
              document.body.insertAdjacentElement("beforeend", pio_container);
              let pio_action = document.createElement("div");
              pio_action.classList.add("pio-action");
              pio_container.insertAdjacentElement("beforeend", pio_action);
              let pio_canvas = document.createElement("canvas");
              pio_canvas.id = "pio";
              pio_canvas.style.width = "14rem";
              pio_canvas.width = "600";
              pio_canvas.height = "800";
              pio_container.insertAdjacentElement("beforeend", pio_canvas);
              let pio = new Paul_Pio({
                "mode": "fixed",
                "hidden": true,
                "night": "for(let i=7; i<16; ++i) if(document.body.classList.contains(`theme-base-0`+i.toString(16))) { document.body.classList.remove(`theme-base-0`+i.toString(16)); document.body.classList.add(`theme-base-0`+((i-6)%9+7).toString(16)); break; }",
                "content": {
                  "link": ["https://jekyll-theme-WuK.wu-kan.cn"],
                  "skin": ["要换成我的朋友吗？", "让她放个假吧~"],
                  "hidden": true,
                  "custom": [{
                    "selector": "a",
                    "type": "link",
                  }, {
                    "selector": ".sidebar-toggle",
                    "text": "打开侧边栏叭~"
                  }, {
                    "selector": ".effect-info",
                    "text": "哇，你发现了什么！"
                  }, {
                    "selector": "#sidebar-search-input",
                    "text": "想搜索什么呢？很多干货哦！"
                  }, {
                    "selector": "#toc",
                    "text": "这是目录~"
                  }, {
                    "selector": ".page-title",
                    "text": "这是标题~"
                  }, {
                    "selector": ".v",
                    "text": "评论没有审核，要对自己的发言负责哦~"
                  }]
                },
                "model": [
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
              });'
        ></script>
      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js	      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
        <script	        <script
          src='https://zz.bdstatic.com/linksubmit/push.js'	          src='https://zz.bdstatic.com/linksubmit/push.js'
@@ -84,9 +156,6 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
        ></script>	        ></script>
      - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在 /assets/image/background.jpg，那就改成 url(/assets/image/background.jpg)	      - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在 /assets/image/background.jpg，那就改成 url(/assets/image/background.jpg)
        <style>	        <style>
          h1,h2,h3,h4,h5,h6,p,em,div,li,strong,b{	
            font-family: 'Roboto', "Palatino Linotype","Book Antiqua",Palatino,FreeSerif,serif !important;	
          }	
          .wrap {	          .wrap {
            transition-property: all;	            transition-property: all;
            transition-duration: .3s;	            transition-duration: .3s;
@@ -154,10 +223,196 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
      disable: false # 是否不显示sidebar	      disable: false # 是否不显示sidebar
      avatar: # 侧边栏显示的头像	      avatar: # 侧边栏显示的头像
        enable: true	        enable: true
        img: https://scontent.fdad1-1.fna.fbcdn.net/v/t31.0-8/p960x960/12973173_842866119180105_1285620276625827169_o.jpg?_nc_cat=105&_nc_sid=7aed08&_nc_oc=AQkp7jEuLaqGwxG0azZY5vr3PNGP83q9l-ML51coGlgSV3QFDxwrEFmhzefJvtcnBV4&_nc_ht=scontent.fdad1-1.fna&_nc_tp=6&oh=4c130edf9eedd9ee2cff8aa0041147a8&oe=5EE40B37 # 头像的地址	        img: https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=320 # 头像的地址
      nav: # Description	      nav: # 导航部分的内容，你也可以自己增加文字、图标（来自fontawesome）和对应的链接
        - title: '<i class="fas fa-home fa-fw"></i> Home'	        - title: '<i class="fas fa-home fa-fw"></i> 首页'
          href: /	          href: /
        - title: '<i class="fas fa-comments fa-fw"></i> 留言'
          href: /comments/
        - title: '<i class="fas fa-tags fa-fw"></i> 标签'
          href: /tags/
        - title: '<i class="fas fa-archive fa-fw"></i> 归档'
          href: /archive/
        - title: '<i class="fas fa-coffee fa-fw"></i> 打赏'
          href: /merger/
      simple_jekyll_search: # 侧边栏的全站搜索
        enable: true
        full_text_search: false # 可能导致缓慢的搜索和加载
        alert: | # 如果看不懂就不改
          <style>
            #sidebar-search-input {
              background: none;
              border: none;
              color: White;
              width: 100%;
            }
            #sidebar-search-results-container {
              overflow: auto auto;
              max-height: 50vh;
            }
          </style>
          <input
            id="sidebar-search-input"
            placeholder="搜索博文"
          />
          <ol
            id="sidebar-search-results-container"
          ></ol>
          <script
            src='https://cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js'
            async='async'
            onload='
              SimpleJekyllSearch({
                json: "/assets/simple-jekyll-search/search.json",
                searchInput: document.getElementById("sidebar-search-input"),
                resultsContainer: document.getElementById("sidebar-search-results-container"),
                searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                limit: 999,
                fuzzy: true
              })'
          ></script>
      append_to_sidebar:
        #- <script defer="defer" src="https://cdn.jsdelivr.net/gh/poole/lanyon@v1.1.0/public/js/script.min.js"></script> # 点击空白处而非按钮从而关闭侧边栏的插件，可选
        - | #修复点击侧边栏按钮回到顶部的问题
          <style>
            .sidebar-checkbox {
              display: none;
            }
            .sidebar-toggle {
              position: fixed;
            }
          </style>
        - | # 侧边栏头像效果
          <style>
            .effect {
              margin: 1rem;
              perspective: 900px;
            }
            .effect-info {
              text-align: center;
              backface-visibility: hidden;
              position: absolute;
              top: 0;
              transform-style: preserve-3d;
            }
            .effect-img {
              z-index: 11;
              width: 100%;
              height: 100%;
              position: relative;
              transition: all 0.5s ease-in-out;
            }
            .effect-img:before {
              position: absolute;
              display: block;
            }
            .effect-right_to_left .effect-img {
              transform-origin: 0% 50%;
            }
            .effect-right_to_left:hover .effect-img {
              transform: rotate3d(0, 1, 0, -180deg);
            }
          </style>
        - | # 目录插件，如果看不懂就不改
          <style>
            #toc {
              overflow: auto auto;
              max-height:50vh;
            }
          </style>
          <aside id="toc">
            目录
          </aside>
          <script
            defer='defer'
            src='https://cdn.jsdelivr.net/npm/html-contents/html-contents.min.js'
            onload="htmlContents('#toc', {listType: 'o', filter: function(arr) {return !arr.matches('.masthead-title')}})"
          ></script>
        - | # 运行时间，可将倒数第三行的时间改成你自己的建站时间，格式仿照上面的；不需要的话可以把这一项都删掉
          <div>
            <i class="fas fa-cog fa-spin fa-fw"></i>
            <span id="run_time_day">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>天
            <span id="run_time_hour">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>时
            <span id="run_time_minute">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>分
            <span id="run_time_second">
              <i class="fas fa-spinner fa-pulse"></i>
            </span>秒
            <script>
              setInterval(function (BirthDay) {
                function setzero(i) {
                  if (i < 10) return "0" + i;
                  return i;
                }
                BirthDay = new Date(BirthDay);
                today = new Date();
                timeold = (today.getTime() - BirthDay.getTime());
                sectimeold = timeold / 1000;
                secondsold = Math.floor(sectimeold);
                msPerDay = 24 * 60 * 60 * 1000;
                e_daysold = timeold / msPerDay;
                daysold = Math.floor(e_daysold);
                e_hrsold = (e_daysold - daysold) * 24;
                hrsold = Math.floor(e_hrsold);
                e_minsold = (e_hrsold - hrsold) * 60;
                minsold = Math.floor((e_hrsold - hrsold) * 60);
                seconds = Math.floor((e_minsold - minsold) * 60);
                document.getElementById("run_time_day").innerHTML = daysold;
                document.getElementById("run_time_hour").innerHTML = setzero(hrsold);
                document.getElementById("run_time_minute").innerHTML = setzero(minsold);
                document.getElementById("run_time_second").innerHTML = setzero(seconds);
              }, 1000, "10/04/2017 11:03:56") // 这是我第一篇CSDN博客的时间
            </script>
          </div>
        - | # 不蒜子页面统计，看不懂可不改
          <div>
            <div>
              <i class="fas fa-eye fa-fw"></i>
              <span id="busuanzi_value_page_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>次
            </div>
            <div>
              <i class="fas fa-paw fa-fw"></i>
              <span id="busuanzi_value_site_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>枚
            </div>
            <div>
              <i class="fas fa-user-friends fa-fw"></i>
              <span id="busuanzi_value_site_uv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>人
            </div>
            <script
              src='https://cdn.jsdelivr.net/npm/busuanzi'
              async='async'
            ></script>
          </div>
        - | # Copyright声明
          <div>
            <i class="fas fa-copyright fa-fw"></i>
            2017-2020 WuK
          </div>
        - | # 觉得我的主题好用的话，让更多的人知道它吧！
          <div>
            <i class="fas fa-thumbs-up fa-fw"></i>
            <a href="https://jekyll-theme-WuK.wu-kan.cn">
              jekyll-theme-WuK
            </a>
          </div>
        - | # 我的备案信息，请你的网站删掉这一项。互联网非法外之地！
          <div>
            <i class="fas fa-info-circle fa-fw"></i>
            <a href="http://beian.miit.gov.cn">
              粤ICP备20024947号
            </a>
          </div>
      wordcount: # 全站字数统计	      wordcount: # 全站字数统计
        enable: false # 本地调试时建议关闭，非常影响站点生成速度（所需时间与博文数量的平方成正比）	        enable: false # 本地调试时建议关闭，非常影响站点生成速度（所需时间与博文数量的平方成正比）
        alert: <i class="fas fa-user-edit fa-fw"></i>	        alert: <i class="fas fa-user-edit fa-fw"></i>
