title: vinhminh # CV
description: | # VM ，<br/>VM
  Hobbies<br/>
  Backpacking, Fishing<br/>
  Game, Movies, Books<br/>
  <a href="mailto:vinhminhthan@gmail.com">
    <i class="fas fa-envelope"></i>
  </a>
  <a href="https://www.facebook.com/ga.gapro.5">
    <i class="fab fa-facebook"></i>
  </a>
  <a href="https://www.linkedin.com/in/minh-v%C4%A9nh-6baba899/">
    <i class="fas fa-linkedin-in"></i>
  </a>
  <iframe
    src="https://music.163.com/outchain/player?type=0&id=155059595&auto=0&height=32"
    width=100%
    height=52
    frameborder="no"
    border="0"
    marginwidth="0"
    marginheight="0"
  ></iframe>
url: https://wu-kan.cn # 你的域名，例如 https://wu-kan.github.io	url: https://wu-kan.cn # 你的域名，例如 https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。	baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。


@@ -62,11 +78,67 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
          rel="stylesheet"	          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"	          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
        />	        />
      - | # 引入live2d看板娘！不需要可以把这一项都删掉	        <script
        <link	          async="async"
          rel="stylesheet"	          src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"	          onload='
        />	              let pio_container = document.createElement("div");
              pio_container.classList.add("pio-container");
              pio_container.classList.add("right");
              pio_container.style.bottom = "-2rem";
              pio_container.style.zIndex = "1";
              document.body.insertAdjacentElement("beforeend", pio_container);
              let pio_action = document.createElement("div");
              pio_action.classList.add("pio-action");
              pio_container.insertAdjacentElement("beforeend", pio_action);
              let pio_canvas = document.createElement("canvas");
              pio_canvas.id = "pio";
              pio_canvas.style.width = "14rem";
              pio_canvas.width = "600";
              pio_canvas.height = "800";
              pio_container.insertAdjacentElement("beforeend", pio_canvas);
              let pio = new Paul_Pio({
                "mode": "fixed",
                "hidden": true,
                "night": "for(let i=7; i<16; ++i) if(document.body.classList.contains(`theme-base-0`+i.toString(16))) { document.body.classList.remove(`theme-base-0`+i.toString(16)); document.body.classList.add(`theme-base-0`+((i-6)%9+7).toString(16)); break; }",
                "content": {
                  "link": ["https://jekyll-theme-WuK.wu-kan.cn"],
                  "skin": ["要换成我的朋友吗？", "让她放个假吧~"],
                  "hidden": true,
                  "custom": [{
                    "selector": "a",
                    "type": "link",
                  }, {
                    "selector": ".sidebar-toggle",
                    "text": "打开侧边栏叭~"
                  }, {
                    "selector": ".effect-info",
                    "text": "哇，你发现了什么！"
                  }, {
                    "selector": "#sidebar-search-input",
                    "text": "想搜索什么呢？很多干货哦！"
                  }, {
                    "selector": "#toc",
                    "text": "这是目录~"
                  }, {
                    "selector": ".page-title",
                    "text": "这是标题~"
                  }, {
                    "selector": ".v",
                    "text": "评论没有审核，要对自己的发言负责哦~"
                  }]
                },
                "model": [
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
              });'
        ></script>
      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js	      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
        <script	        <script
          src='https://zz.bdstatic.com/linksubmit/push.js'	          src='https://zz.bdstatic.com/linksubmit/push.js'
@@ -84,9 +156,6 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
        ></script>	        ></script>
      - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在 /assets/image/background.jpg，那就改成 url(/assets/image/background.jpg)	      - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在 /assets/image/background.jpg，那就改成 url(/assets/image/background.jpg)
        <style>	        <style>
          h1,h2,h3,h4,h5,h6,p,em,div,li,strong,b{	
            font-family: 'Roboto', "Palatino Linotype","Book Antiqua",Palatino,FreeSerif,serif !important;	
          }	
          .wrap {	          .wrap {
            transition-property: all;	            transition-property: all;
            transition-duration: .3s;	            transition-duration: .3s;
@@ -154,10 +223,196 @@ jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
      disable: false # 是否不显示sidebar	      disable: false # 是否不显示sidebar
      avatar: # 侧边栏显示的头像	      avatar: # 侧边栏显示的头像
        enable: true	        enable: true
        img: https://scontent.fdad1-1.fna.fbcdn.net/v/t31.0-8/p960x960/12973173_842866119180105_1285620276625827169_o.jpg?_nc_cat=105&_nc_sid=7aed08&_nc_oc=AQkp7jEuLaqGwxG0azZY5vr3PNGP83q9l-ML51coGlgSV3QFDxwrEFmhzefJvtcnBV4&_nc_ht=scontent.fdad1-1.fna&_nc_tp=6&oh=4c130edf9eedd9ee2cff8aa0041147a8&oe=5EE40B37 # Avatar
      nav: # Description
        - title: '<i class="fas fa-home fa-fw"></i> Home'
