title: vinhminh # vm
description: | # VM ，<br/>VM
  Hobbies:<br/>
  Backpacking, Fishing</br>
  Game, Movies, Books</br>
jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
  default:
    body:
      theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
      layout-reverse: true # 开启后sidebar在右边，反之左边
      sidebar-overlay: true # 开启后正文不随sidebar移动而移动
    append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
      - | #一些页面优化标签，看不懂可跳过
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        />
        <meta
          http-equiv="content-type"
          content="text/html; charset=utf-8"
        />
        <link
          rel="alternate"
          href="/feed.xml"
          title="RSS"
          type="application/rss+xml"
        />
      - | # 网站小图标，可换成你自己的图片，改href中的部分即可
        <link
          rel="apple-touch-icon-precomposed"
          href="https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/10885413_614629395337113_6735444425895489757_n.jpg?_nc_cat=102&_nc_sid=7aed08&_nc_oc=AQnBkeflLtfEcBgFYHCNk9D5lvS1wSPpjSky-oBqq_mcVCngyyyzomxJgbwhfr8dIMo&_nc_ht=scontent.fdad1-1.fna&oh=558b0ef8f4fcd63dbc76c1cbfbfd8202&oe=5EF55FF3"
        />
        <link
          rel="shortcut
          icon"
          href="https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/10885413_614629395337113_6735444425895489757_n.jpg?_nc_cat=102&_nc_sid=7aed08&_nc_oc=AQnBkeflLtfEcBgFYHCNk9D5lvS1wSPpjSky-oBqq_mcVCngyyyzomxJgbwhfr8dIMo&_nc_ht=scontent.fdad1-1.fna&oh=558b0ef8f4fcd63dbc76c1cbfbfd8202&oe=5EF55FF3"
        />
      - | # 来自lanyon的页面样式，不要改
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@v1.1.0/public/css/poole.min.css,gh/poole/lanyon@v1.1.0/public/css/lanyon.min.css"
        />
      - | # 引入fontawesome图标样式
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css"
        />
      - | # Font
        <link	async="async" rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"	 />
      - | # 引入live2d看板娘！不需要可以把这一项都删掉
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
        />
        
        <!--<script
          async="async"
          src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
          onload='
              let pio_container = document.createElement("div");
              pio_container.classList.add("pio-container");
              pio_container.classList.add("right");
              pio_container.style.bottom = "-2rem";
              pio_container.style.zIndex = "1";
              document.body.insertAdjacentElement("beforeend", pio_container);
              let pio_action = document.createElement("div");
              pio_action.classList.add("pio-action");
              pio_container.insertAdjacentElement("beforeend", pio_action);
              let pio_canvas = document.createElement("canvas");
              pio_canvas.id = "pio";
              pio_canvas.style.width = "14rem";
              pio_canvas.width = "600";
              pio_canvas.height = "800";
              pio_container.insertAdjacentElement("beforeend", pio_canvas);
              let pio = new Paul_Pio({
                "mode": "fixed",
                "hidden": true,
                "night": "for(let i=7; i<16; ++i) if(document.body.classList.contains(`theme-base-0`+i.toString(16))) { document.body.classList.remove(`theme-base-0`+i.toString(16)); document.body.classList.add(`theme-base-0`+((i-6)%9+7).toString(16)); break; }",
                "content": {
                  "link": ["https://jekyll-theme-WuK.wu-kan.cn"],
                  "skin": ["要换成我的朋友吗？", "让她放个假吧~"],
                  "hidden": true,
                  "custom": [{
                    "selector": "a",
                    "type": "link",
                  }, {
                    "selector": ".sidebar-toggle",
                    "text": "打开侧边栏叭~"
                  }, {
                    "selector": ".effect-info",
                    "text": "哇，你发现了什么！"
                  }, {
                    "selector": "#sidebar-search-input",
                    "text": "想搜索什么呢？很多干货哦！"
                  }, {
                    "selector": "#toc",
                    "text": "这是目录~"
                  }, {
                    "selector": ".page-title",
                    "text": "这是标题~"
                  }, {
                    "selector": ".v",
                    "text": "评论没有审核，要对自己的发言负责哦~"
                  }]
                },
                "model": [
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                  "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
              });'
        ></script>-->
      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
        <script
          src='https://zz.bdstatic.com/linksubmit/push.js'
          async="async"
        ></script>
        <style>
          .wrap {
            transition-property: width,background-size,transform;
            transition-duration: .3s;
            transition-timing-function: ease-in-out;
            min-height: 100%;
            display: inline-block;
            background-size: cover;
            background-position: 0% 0%;
            background-repeat: no-repeat;
            background-attachment: fixed;
            bac
            background-image: url(https://saigon-gpdaily.com.vn/wp-content/uploads/2018/08/hinh-nen-powerpoint-dep-6.jpg);
          }
          @media (min-aspect-ratio: 2400/1850) {
            .wrap {
              background-image: url(https://saigon-gpdaily.com.vn/wp-content/uploads/2018/08/hinh-nen-powerpoint-dep-6.jpg);
            }
          }
          .sidebar-overlay #sidebar-checkbox:checked ~ .wrap {
            width: calc(100% - 14rem);
            background-size: calc(100% - 14rem) auto;
            transform: translateX(14rem);
          }
          .layout-reverse.sidebar-overlay #sidebar-checkbox:checked ~ .wrap {
            transform: translateX(0);
          }
        </style>
      - | # VM
        <style>
          .sidebar,
          html,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6 {
            font-family: 'Roboto', "Palatino Linotype","Book Antiqua",Palatino,FreeSerif,serif !important;	
          }
          .sidebar a:focus, .sidebar a:hover{text-decoration:none}
        </style>
      - | # VM
        <style>
          h1,
          h2,
          h3,
          h4,
          h5,
          h6 {
            font-weight: bold;
          }
        </style>
      - | # VM
        <style>
          img {
            display: inline-block;
            margin: 0;
          }
        </style>
      - | # VM
        <style>
          ::-webkit-scrollbar {
            width: 3px;
            height: 3px;
          }
          ::-webkit-scrollbar-thumb {
            background-image: linear-gradient(45deg, Cyan 0%, Magenta 50%, Yellow 100%);
          }
        </style>
      - | # VM
        <style>
          ::selection {
            color: White;
            background: Black;
          }
        </style>
    sidebar: # sidebar
      disable: false # disable
      avatar: # Avatar
        enable: true
        img: https://scontent.fdad1-1.fna.fbcdn.net/v/t31.0-8/p960x960/12973173_842866119180105_1285620276625827169_o.jpg?_nc_cat=105&_nc_sid=7aed08&_nc_oc=AQkp7jEuLaqGwxG0azZY5vr3PNGP83q9l-ML51coGlgSV3QFDxwrEFmhzefJvtcnBV4&_nc_ht=scontent.fdad1-1.fna&_nc_tp=6&oh=4c130edf9eedd9ee2cff8aa0041147a8&oe=5EE40B37 # Avatar
      nav: # Description
        - title: '<i class="fas fa-home fa-fw"></i> Home'
          href: /
      
      append_to_sidebar:
        #- <script defer="defer" src="https://cdn.jsdelivr.net/gh/poole/lanyon@v1.1.0/public/js/script.min.js"></script> # VM
        - | # VM
          <style>
            .sidebar-checkbox {
              display: none;
            }
            .sidebar-toggle {
              position: fixed;
            }
          </style>
        - | # VM
          <style>
            .effect {
              margin: 1rem;
              perspective: 900px;
            }
            .effect-info {
              text-align: center;
              backface-visibility: hidden;
              position: absolute;
              top: 0;
              transform-style: preserve-3d;
            }
            .effect-img {
              z-index: 11;
              width: 100%;
              height: 100%;
              position: relative;
              transition: all 0.5s ease-in-out;
            }
            .effect-img:before {
              position: absolute;
              display: block;
            }
            .effect-right_to_left .effect-img {
              transform-origin: 0% 50%;
            }
            .effect-right_to_left:hover .effect-img {
              transform: rotate3d(0, 1, 0, -180deg);
            }
          </style>
        - | # Copyright
          <div>
           <p>Date of birth:  Mar 18, 1990<br/>
            Gender: Male<br/>
            Phone: 0779623272<br/>
            Address QNam, Vietnam<br/></p>
            <p>
              <a href="mailto:vinhminhthan@gmail.com">
                <i class="fas fa-envelope"></i>
              </a>
              <a href="https://www.facebook.com/ga.gapro.5">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="https://www.linkedin.com/in/minh-v%C4%A9nh-6baba899/">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </p>
          </div>
  home: # Home
    append_to_section_tag:
      - key: data-markdown
      - key: data-separator # 水平展示页分隔符
        value: <!-- slide -->
      - key: data-separator-vertical # 垂直展示页分隔符
        value: <!-- slide vertical=true -->
      - key: data-background-color
        value: "White"
    prepend: |
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.0.0/dist/reveal.min.css,npm/reveal.js@4.0.0/dist/theme/serif.min.css"
      />
      <style>
        .sidebar {
          line-height: 1.5;
        }
        .reveal .slides {
          text-align: left;
        }
        .reveal a {
          color: #268BD2;
        }
      </style>
      <script
        defer="defer"
        src="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.0.0/dist/reveal.min.js,npm/reveal.js@4.0.0/plugin/markdown/markdown.js"
        onload="
        document.getElementsByClassName('wrap')[0].classList.add('reveal');
        Reveal.initialize({
          height: '100%',
          hash: true,
          mouseWheel: true,
          navigationMode: 'linear',
          plugins: [ RevealMarkdown ]
        });
      "></script>
  document:
    append_to_head:
      - |
        <meta
          content="width=device-width, initial-scale=1"
          name="viewport"
        />
      - |
        <link
          href="https://cdn.jsdelivr.net/npm/github-markdown-css@4.0.0/github-markdown.min.css"
          rel="stylesheet"
        />
      - | # 仿 github 页面样式；打印时字体换成宋体更美观
        <style>
          .markdown-body {
            box-sizing: border-box;
            min-width: 200px;
            max-width: 980px;
            margin: 0 auto;
            padding: 45px;
          }
          @media (max-width: 767px) {
            .markdown-body { padding: 15px; }
          }
          @media print {
            h1 { page-break-before: always; }
            .markdown-body { font-family: "Palatino Linotype","Book Antiqua",Palatino,FreeSerif,serif; }
          }
        </style>
  page404:
    prepend:
      - | # 腾讯公益
        <script
          src='https://qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js'
          async='async'
          charset='utf-8'
          homePageUrl='/'
          homePageName='回到我的主页'
        ></script>

# githubpage上支持的插件见<https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源
  - jekyll-remote-theme # 使用remote_theme插件实现主题的前后分离，详见<https://github.com/benbalter/jekyll-remote-theme/>

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@3.2.0 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

permalink: /_posts/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样
# timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见<https://www.iana.org/time-zones>
# future: false # 不发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    disable: true # 关掉默认的高亮，换用prismjs
